Add an NSUpdate class, that we can then use instead of calling nsupdate directly
darcs-hash:20070803100613-6856b-23a0a3af9f5a4447b191091abd0c89875a1c9ded.gz

diff --git a/test/fixtures/nsupdate b/test/fixtures/nsupdate
--- a/test/fixtures/nsupdate
+++ b/test/fixtures/nsupdate
@@ -8,3 +8,7 @@ if [ -n "$FAUX_NSUPDATE_KEY" ]; then
 fi
 
 /bin/cat >> $FAUX_NSUPDATE_OUTPUT
+
+if /bin/grep 'server timeout' $FAUX_NSUPDATE_OUTPUT; then
+	/bin/echo "; Communication with server failed: timed out" >&2
+fi
